Algoritmo "FuncaoSomar"
//
// Funcao
// Neste algoritmo, o sistema ira somar duas variaveis atraves de funcao

Var
// Na funcao, diferentemente do procedimento, nao e necessario declarar variaveis em VAR

// Na funcao, e necessario declarar o tipo do retorno
Funcao somar(x,y: inteiro): inteiro
Inicio
    retorne x+y
FimFuncao

Inicio
    // Para visualizar o resultado, basta chamar a funcao
    Escreva("10 + 20 =", somar(10,20))
    Escreva("")
Fimalgoritmo